import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EditorLayout } from "@/components/editor/editor-layout";
import { EditorProvider } from "@/components/editor/editor-context";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorBackground: "var(--background)",
          colorText: "var(--foreground)",
          colorTextSecondary: "var(--muted-foreground)",
          colorInputBackground: "var(--input)",
          colorInputText: "var(--foreground)",
          colorPrimary: "var(--primary)",
          colorDanger: "var(--destructive)",
          borderRadius: "var(--radius)",
          fontFamily: "var(--font-geist-sans)",
        },
      } as any}>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <EditorProvider>
            <EditorLayout>{children}</EditorLayout>
          </EditorProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
